// API keys are compile-time only — pass via --dart-define (see README).
// Do not commit real keys to source control.
//
// --dart-define=GEMINI_API_KEY=...
// --dart-define=GEMINI_OLD_KEY=...
// --dart-define=GROQ_API_KEY=...
// --dart-define=OPENROUTER_API_KEY=...
